### ISSUE TITLE
+ button not working 

### ISSUE THREAD

**Issue by Rick-mad-lab** [Rick-mad-lab/Todolist#21]
+ button working in the previous version not now fix it.

**Comment by superiorsd10** [comment]
@Rick-mad-lab I would like to work on this issue. Can you please assign it to me?

**Comment by mananchawla2005** [comment]
can you assign?

**Comment by Jaammeesss** [comment]
My PR Should fix this bug aswell please merge :)

**Comment by lognoroy** [comment]
Please give me a chance . I want to contribute.

**Comment by poonam-kumawat** [comment]
I am able to do this. Can you please assign it to me?

**Comment by Rick-mad-lab** [comment]
fixed by maintainer
