### ISSUE TITLE
Add new card component 

### ISSUE THREAD

**Issue by Rick-mad-lab** [Rick-mad-lab/Todolist#3]

**Comment by thisisharsh7** [comment]
I would like to work on this issue. can you assign it to me.

**Comment by thisisharsh7** [comment]
It would be helpful if you could give me a little more information about the work I have to complete.

**Comment by lakshyaagr1105** [comment]
Hey Rick-mad-lab, I am Lakshya and I am a FrontEnd Developer, can you please assign me this project, i am highly interested

**Comment by Rick-mad-lab** [comment]
yes, but I can't assign the same work.

**Comment by Rick-mad-lab** [comment]
@lakshyaagr1105 and @thisisharsh7 share your thoughts here then I will assign you.

**Comment by thisisharsh7** [comment]
Please provide me with more information about the task if you are assigning it to me.


> @lakshyaagr1105 and @thisisharsh7 share your thoughts here then I will assign you.

**Comment by lakshyaagr1105** [comment]
> @lakshyaagr1105 and @thisisharsh7 share your thoughts here then I will assign you.

I just viewed your project and the problems i can fix are
1. The styling is not right.
2. Can be more subtle.
3. Refactor your code

**Comment by Devesh18Sharma** [comment]
Assign it to me...I will ensure it looks good and the card component matches the website design...

**Comment by Rick-mad-lab** [comment]
@Devesh18Sharma 
go for it.

**Comment by Kritika30032002** [comment]
May I contribute to this ?
Is this still available?

**Comment by Rick-mad-lab** [comment]
yes just enhance the card of to do

**Comment by Kritika30032002** [comment]
Which kind of effects you want?
Any specific requirement?
Or I have to do it on my own/
