### ISSUE TITLE
wanted to add contributing.md file

### ISSUE THREAD

**Issue by Nirbhayparmar** [Rick-mad-lab/Todolist#36]
Hello, @Rick-mad-lab , I like your project, I think it should have a contributing.md file to help beginners to contribute to your project. I can make such file, which contains all the details like steps before making your changes in code to making your first pull request. 

Can you assign me this issue so I can work on it as a part of hacktoberfest2022?

**Comment by Rick-mad-lab** [comment]
yep, you can on this one!

**Comment by BTANISHA11** [comment]
I want to work on contributing.md 
Can you pls assign this to me @Rick-mad-lab
