### ISSUE TITLE
Better documentation needed. 

### ISSUE THREAD

**Issue by Rick-mad-lab** [Rick-mad-lab/Todolist#4]

**Comment by Prajwal0225** [comment]
I want to contribute to documentation . Can you please assign me this?

**Comment by aanchal-fatwani** [comment]
Hi @Rick-mad-lab, I'd like to work on this issue. I have a structure in mind to create good documentation(with sub-sections, and links - for ease of reading, setup steps, tech, and folder structure, features, scope, etc)
I think I'll be able to better contribute to this issue.
Please assign me this to allow me to proceed with the same. Thanks.

**Comment by Rick-mad-lab** [comment]
all yours!
