### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by partik03** [Rick-mad-lab/Todolist#43]
Current UI/Ux is not that impressive 
![Screenshot from 2022-10-02 01-19-26](https://user-images.githubusercontent.com/99184676/193425916-adb26d35-2690-44e8-951f-9cab64fc619c.png)

**Comment by partik03** [comment]
I have added my pr kindly review it

**Comment by Rick-mad-lab** [comment]
new UI has already been Implemented.
