### ISSUE TITLE
Introduce new design 

### ISSUE THREAD

**Issue by Rick-mad-lab** [Rick-mad-lab/Todolist#5]

**Comment by nIMblEt06** [comment]
i could give you a design for your project, if you could assign the issue to me.

**Comment by Rick-mad-lab** [comment]
no issue It's all yours. @nIMblEt06

**Comment by MSamiDev** [comment]
Hello @nIMblEt06  
as this I no-code contribution. so we can do it together you can design and I will look after the code part.

Hey @Rick-mad-lab  what do you think.

**Comment by nIMblEt06** [comment]
@Rick-mad-lab i have designed the new UI for the website, please check it out on this link, and tell how am i supposed to add a PR for this if we're going forward with this design.
https://www.figma.com/file/e4UwiTlSW8gBdwzlz9fgJQ/toDoList?node-id=0%3A1

**Comment by MSamiDev** [comment]
> @Rick-mad-lab i have designed the new UI for the website, please check it out on this link, and tell how am i supposed to add a PR for this if we're going forward with this design.
> https://www.figma.com/file/e4UwiTlSW8gBdwzlz9fgJQ/toDoList?node-id=0%3A1

hello @nIMblEt06 
cool design.

@Rick-mad-lab  shall I do the code for this design...?
