### ISSUE TITLE
Add github repo stats in README.md

### ISSUE THREAD

**Issue by galahad42** [Rick-mad-lab/Todolist#50]
We can add a github repo stats in README.md to make it more informative.
Something like this:
![192417213-d554e0f4-faa5-4841-88ec-9f8e31d26bac](https://user-images.githubusercontent.com/59364507/193428719-7bef2137-ae0a-4af6-a832-5e8a7c6e4e52.png)

I can work on it under hactoberfest 2022.

**Comment by Rick-mad-lab** [comment]
ok lovely

**Comment by Rick-mad-lab** [comment]
nicely done
