### ISSUE TITLE
Hey can I contribute to the UI ?

### ISSUE THREAD

**Issue by shashank-iter** [Rick-mad-lab/Todolist#57]
Hey, I contributed to 5 projects since the hacktober fest has started, I just saw your repository and I really want to contribute to enhance the UI of the website can I contribute ??

**Comment by Rick-mad-lab** [comment]
you can work on UI @shashank-iter but go to Discussions tab to introduce your idea.

**Comment by shashank-iter** [comment]
okay surely be doing that
