### ISSUE TITLE
Code of Conduct for contributing

### ISSUE THREAD

**Issue by kumar-kalyan** [Rick-mad-lab/Todolist#9]

**Comment by sakshi135** [comment]
i want to contribute in this. please assign me this.

**Comment by Rick-mad-lab** [comment]
This one is already assigned to @kumar-kalyan.
Ask him about this

**Comment by Rick-mad-lab** [comment]
done!
great @kumar-kalyan 
sorry, @sakshi135, This task is already assigned.
