### ISSUE TITLE
Customize the dark mode button

### ISSUE THREAD

**Issue by zugzwang03** [Rick-mad-lab/Todolist#98]
As we can see the button has only the moon symbol on it, I want to also add up the sun symbol, and make some changes on the overall designing to make it look attractive

![dark](https://user-images.githubusercontent.com/95460021/196229377-0ae28f27-1e26-4f46-865c-8f9b24b8daaf.png)

**Comment by Rick-mad-lab** [comment]
ok
go for it

**Comment by zugzwang03** [comment]
These are my changes, kindly review them :

https://user-images.githubusercontent.com/95460021/197135453-cc4d8fd7-e3ac-4d05-98b1-e27e6e3ff4d9.mp4

**Comment by zugzwang03** [comment]
@Rick-mad-lab
